### ISSUE TITLE
fail on iOS 13

### ISSUE THREAD

**Issue by alexsunday** [SiriDx/qrcode#13]
exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureSession addInput:] Can't add a nil AVCaptureInput'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   AVFoundation                        0x00007fff20908783 -[AVCaptureSession addInput:] + 1058
	3   qrcode                              0x000000010f47eecc -[QRCaptureView initWithFrame:viewIdentifier:arguments:registrar:] + 1100
	4   qrcode                              0x000000010f47e785 -[QRCapturePlatformView initWithFrame:viewIdentifier:arguments:registrar:] + 261
	5   qrcode                              0x000000010f47fd11 -[QRCaptureViewFactory createWithFrame:viewIdentifier:arguments:] + 193
	6   Flutter                             0x000000010d27d2d1 _ZN7flutter30FlutterPlatformViewsController8OnCreateEP17FlutterMethodCallRU13block_pointerFvP11objc_objectE + 707
	7   Flutter                             0x000000010d278321 __47-[FlutterEngine maybeSetupPlatformViewChannels]_block_invoke.127 + 38
	8   Flutter                             0x000000010d2ffb35 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	9   Flutter                             0x000000010d293920 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	10  Flutter                             0x000000010d2973ce _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	11  Flutter                             0x000000010d2f96e9 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_32NS_9allocatorIS8_EEFvvEEclEv + 57
	12  Flutter                             0x000000010d2a68f3 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 117
	13  Flutter                             0x000000010d2ab638 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	14  CoreFoundation                      0x00007fff23d9e634 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	15  CoreFoundation                      0x00007fff23d9e2ce __CFRunLoopDoTimer + 1038
	16  CoreFoundation                      0x00007fff23d9d92a __CFRunLoopDoTimers + 282
	17  CoreFoundation                      0x00007fff23d9857e __CFRunLoopRun + 1950
	18  CoreFoundation                      0x00007fff23d97ac4 CFRunLoopRunSpecific + 404
	19  GraphicsServices                    0x00007fff38b2fc1a GSEventRunModal + 139
	20  UIKitCore                           0x00007fff48bc7f80 UIApplicationMain + 1605
	21  Runner                              0x000000010cfe7a8b main + 75
	22  libdyld.dylib                       0x00007fff519521fd start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by lp7799** [comment]
**Is there a solution to the same mistake?**

**Comment by alexsunday** [comment]
> **Is there a solution to the same mistake?**

use real iPhone not emulator will fix it

**Comment by ghozay19** [comment]
> > **Is there a solution to the same mistake?**
> 
> use real iPhone not emulator will fix it

so it fixed when u re using real device?

**Comment by lauro-cesar** [comment]
Hi, to avoid crashing using simulator you need to add a check if device is not nil at line #49 of QRCaptureView.m.

or use my fork while the author fix or change somehow...

  qrcode:
    git:
      url: git@github.com:sharedway/qrcode.git
      ref: 0.0.2 #tag
      path: qrcode
