### ISSUE TITLE
Can't set width and height on iOS

### ISSUE THREAD

**Issue by sbd2015** [SiriDx/qrcode#3]
First of all, thank you for the library. It's one of the very few libraries that you can fit camera view in a widget with working torch plus it doesn't require android minumum sdk 21.
So everything worked perfectly in Android. But I encountered the problem where I can't quite set width and height of the QRCaptureView in iOS. I treid to wrap in Container but the QRCaptureView always has the defualt size that fit between my appbar and bottom navigation bar that I have in my app then it would ignore container width and height and go across the boundary. So it doesn't cover entrie screen but I can't get it smaller. I tested on iPhone5s and 8.

**Comment by SiriDx** [comment]
fix in 1.03, please update dependencie to
qrcode: ^1.0.3
https://pub.dev/packages/qrcode/versions/1.0.3
